name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      working-directory: ./backend/BankManagement.API
      run: dotnet restore
    
    - name: Build
      working-directory: ./backend/BankManagement.API
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      working-directory: ./backend/BankManagement.API
      run: dotnet test --no-build --verbosity normal --configuration Release
    
    - name: Publish
      working-directory: ./backend/BankManagement.API
      run: dotnet publish -c Release -o ../../publish --no-restore
